# Generated by Django 4.2.1 on 2023-06-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomm_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discounted_price",
            field=models.DecimalField(decimal_places=2, default=23, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="profileimg",
            field=models.ImageField(
                default="blank_profile_pic.jpg", upload_to="media/images"
            ),
        ),
    ]
