# Generated by Django 4.2.1 on 2023-06-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomm_app", "0002_product_discounted_price_product_profileimg"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_short_note",
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="profileimg",
            field=models.ImageField(
                default="media/images/blank_profile_pic.jpg", upload_to="media/images"
            ),
        ),
    ]
