# Generated by Django 4.2.1 on 2023-06-06 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecomm_app", "0003_product_product_short_note_alter_product_profileimg"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ecomm_app.category",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seller",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ecomm_app.category",
            ),
            preserve_default=False,
        ),
    ]
