# Generated by Django 4.2.1 on 2023-06-06 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecomm_app", "0004_brand_category_seller_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="warranty",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ecomm_app.category",
            ),
            preserve_default=False,
        ),
    ]
