# Generated by Django 4.2.1 on 2023-06-06 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecomm_app", "0005_warranty_category"),
    ]

    operations = [
        migrations.RemoveField(model_name="brand", name="category",),
        migrations.RemoveField(model_name="seller", name="category",),
        migrations.RemoveField(model_name="warranty", name="category",),
    ]
